const flags = [
	{ id: 2, name: "Albania", image: "assets/images/flags/albania.png"},
	{ id: 3, name: "Andorra", image: "assets/images/flags/andorra.png" },
	{ id: 4, name: "Armenia", image: "assets/images/flags/armenia.png" },
	{ id: 6, name: "Austria", image: "assets/images/flags/austria.png" },
	{ id: 7, name: "Belarus", image: "assets/images/flags/belarus.png" },
	{ id: 8, name: "Belgium", image: "assets/images/flags/belgium.png" },
	{ id: 9, name: "Bulgaria", image: "assets/images/flags/bulgaria.png" },
	{ id: 10, name: "Croatia", image: "assets/images/flags/croatia.png" },
	{ id: 11, name: "Cyprus", image: "assets/images/flags/cyprus.webp" },
	{ id: 12, name: "Czech Republic", image: "assets/images/flags/czech-republic.png" },
	{ id: 13, name: "Denmark", image: "assets/images/flags/denmark.png" },
	{ id: 14, name: "Estonia", image: "assets/images/flags/estonia.png" },
	{ id: 15, name: "Finland", image: "assets/images/flags/finland.png" },
	{ id: 16, name: "France", image: "assets/images/flags/france.webp" },
	{ id: 17, name: "Georgia", image: "assets/images/flags/georgia.png" },
	{ id: 18, name: "Germany", image: "assets/images/flags/germany.webp" },
	{ id: 20, name: "Greece", image: "assets/images/flags/greece.png" },
	{ id: 21, name: "Hungary", image: "assets/images/flags/hungary.webp" },
	{ id: 22, name: "Iceland", image: "assets/images/flags/iceland.png" },
	{ id: 25, name: "Italy", image: "assets/images/flags/italy.png" },
	{ id: 26, name: "Latvia", image: "assets/images/flags/latvia.png" },
	{ id: 27, name: "Lithuania", image: "assets/images/flags/lithuania.png" },
	{ id: 28, name: "Macedonia", image: "assets/images/flags/macedonia.png" },
	{ id: 29, name: "Malta", image: "assets/images/flags/malta.png" },
	{ id: 30, name: "Moldova", image: "assets/images/flags/moldova.png" },
	{ id: 31, name: "Montenegro", image: "assets/images/flags/montenegro.png" },
	{ id: 32, name: "Netherlands", image: "assets/images/flags/netherlands.webp" },
	{ id: 33, name: "Norway", image: "assets/images/flags/norway.webp" },
	{ id: 34, name: "Portugal", image: "assets/images/flags/portugal.png" },
	{ id: 35, name: "Romania", image: "assets/images/flags/romania.webp" },
	{ id: 37, name: "Russia", image: "assets/images/flags/russia.webp" },
	{ id: 38, name: "Scotland", image: "assets/images/flags/scotland.webp" },
	{ id: 39, name: "Serbia", image: "assets/images/flags/serbia.png" },
	{ id: 40, name: "Slovakia", image: "assets/images/flags/slovakia.png" },
	{ id: 41, name: "Slovenia", image: "assets/images/flags/slovenia.png" },
	{ id: 42, name: "Spain", image: "assets/images/flags/spain.png" },
	{ id: 45, name: "Sweden", image: "assets/images/flags/sweden.png" },
	{ id: 43, name: "Switzerland", image: "assets/images/flags/switzerland.webp" },
	{ id: 44, name: "Turkey", image: "assets/images/flags/turkey.webp" },
	{ id: 47, name: "Ukraine", image: "assets/images/flags/ukraine.webp" },
	{ id: 48, name: "United Kingdom", image: "assets/images/flags/united-kingdom.png" },
];
